# Generated by Django 2.1.1 on 2018-09-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48)),
                ('author', models.CharField(max_length=48)),
                ('year', models.IntegerField(max_length=4)),
                ('status', models.CharField(choices=[('available', 'Available'), ('out', 'Checked out')], default='out', max_length=48)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_borrowed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
